// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin.sql

package db

import (
	"context"
)

const fetchAdminIDByEmail = `-- name: FetchAdminIDByEmail :one
SELECT adminID
FROM admin
WHERE email = ?
`

func (q *Queries) FetchAdminIDByEmail(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRowContext(ctx, fetchAdminIDByEmail, email)
	var adminid int32
	err := row.Scan(&adminid)
	return adminid, err
}
