// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: registration.sql

package db

import (
	"context"
)

const getRegistrationStatus = `-- name: GetRegistrationStatus :one
SELECT COUNT(*) > 0 AS is_registered
FROM ActivityRegistration
WHERE activityID = ? AND memberID = ?
`

type GetRegistrationStatusParams struct {
	Activityid int32 `json:"activityid"`
	Memberid   int32 `json:"memberid"`
}

func (q *Queries) GetRegistrationStatus(ctx context.Context, arg GetRegistrationStatusParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, getRegistrationStatus, arg.Activityid, arg.Memberid)
	var is_registered bool
	err := row.Scan(&is_registered)
	return is_registered, err
}

const insertRegistration = `-- name: InsertRegistration :exec
INSERT INTO ActivityRegistration (activityID, memberID, role, expectation, datetime)
VALUES (?, ?, ?, ?, NOW())
`

type InsertRegistrationParams struct {
	Activityid  int32  `json:"activityid"`
	Memberid    int32  `json:"memberid"`
	Role        string `json:"role"`
	Expectation string `json:"expectation"`
}

func (q *Queries) InsertRegistration(ctx context.Context, arg InsertRegistrationParams) error {
	_, err := q.db.ExecContext(ctx, insertRegistration,
		arg.Activityid,
		arg.Memberid,
		arg.Role,
		arg.Expectation,
	)
	return err
}
