services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    # working_dir value has to be the same of mapped volume
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      start_period: 20s
      start_interval: 5s
      timeout: 2s
      interval: 1m
      retries: 10
    working_dir: /usr/src/app/
    ports:
      - 8081:8081
    env_file: ".env"
    volumes:
      - ./src/server/:/usr/src/app/
      - server-tmp:/usr/src/app/tmp/
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=ClubManagement
      - LISTEN_PORT=8081
    develop:
      watch:
        - action: sync+restart
          path: ./src/server/
          target: /usr/src/app/
        - action: sync+restart
          path: ./config/.air.toml
          target: /usr/src/app/.air.toml
  frontend:
    container_name: frontend
    environment:
      VITE_API_DOMAIN: "http://server:8081"
    env_file: ".env"
    volumes:
      - ./src/frontend/:/usr/src/app/
      - node_modules:/usr/src/app/node_modules
    build:
      target: dev
      context: .
      dockerfile: ./Dockerfile.frontend
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/health"]
      start_interval: 5s
      start_period: 30s
      timeout: 2s
      interval: 1m
      retries: 10
    develop:
      watch:
        - action: sync
          path: ./src/frontend/
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - 5173:5173
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d/
    depends_on:
      server:
        condition: service_healthy
      frontend:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./config/nginx/nginx.conf
          target: /etc/nginx/conf.d/nginx.conf
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file: ".env"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    command: --lower_case_table_names=1
    ports:
      - "3306:3306"
    volumes:
      - ./src/mysql/scripts/:/docker-entrypoint-initdb.d/
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  node_modules:
  server-tmp:
