FROM golang:alpine AS air

RUN go install github.com/air-verse/air@latest
COPY ./config/.air.toml /etc/.air.toml

FROM air
COPY ./src/server/ /usr/src/app
WORKDIR /usr/src/app

RUN go mod tidy

ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV SESSION_KEY=$SESSION_KEY
ENV LISTEN_PORT=8081

EXPOSE 8081:$LISTEN_PORT

CMD air --build.cmd "go build -o main.o main.go" --build.bin "./main.o" -c /etc/.air.toml

