FROM cosmtrek/air
COPY ./src/server/ /usr/src/app
COPY ./config/.air.toml /usr/src/app
WORKDIR /usr/src/app

RUN go mod tidy

ENV LISTEN_PORT=8081
ENV REDIRECT_PORT=8080

EXPOSE 8081:$LISTEN_PORT

CMD air -c .air.toml