services:
  server:
    container_name: server
    build: 
      dockerfile: ./Dockerfile.server
    volumes:
      - ./src/server/:/usr/app/
    expose:
      - 8081:8081
  frontend:
    container_name: frontend
    build: 
      dockerfile: ./Dockerfile.frontend
    volumes:
      - ./src/frontend/:/usr/app/
    expose:
      - 8082:8080
  nginx:
    image: nginx:1.19.4
    depends_on:
      - server
      - frontend
    volumes:
      - ./src/reverse_proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
 
