services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    # working_dir value has to be the same of mapped volume
    working_dir: /usr/app/
    ports:
      - 8081:8081
    env_file: ".env"
    volumes:
      - ./src/server/:/usr/app/
      - /usr/app/tmp/
  frontend:
    container_name: frontend
    environment:
      VITE_API_DOMAIN: "http://server:8081"
    env_file: ".env"
    volumes:
      - ./src/frontend/:/usr/src/app/
      - /usr/src/app/node_modules
    build:
      target: dev
      context: .
      dockerfile: ./Dockerfile.frontend
    develop:
      watch:
        - action: sync
          path: ./src/frontend/
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - 5173:5173
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d/
    develop:
      watch:
        - action: sync+restart
          path: ./config/nginx/nginx.conf
          target: /etc/nginx/conf.d/nginx.conf
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'ClubManagement'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: