// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: db.sql

package db

import (
	"context"
)

const getMembers = `-- name: GetMembers :many

SELECT memberid, fname, lname, email, phone, githuburl, interest, reason, acceptdatetime, acceptadmin FROM Member
`

func (q *Queries) GetMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.QueryContext(ctx, getMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.Memberid,
			&i.Fname,
			&i.Lname,
			&i.Email,
			&i.Phone,
			&i.Githuburl,
			&i.Interest,
			&i.Reason,
			&i.Acceptdatetime,
			&i.Acceptadmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
