// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Activity struct {
	Activityid        int32
	Title             string
	Proposer          int32
	Startdate         time.Time
	Enddate           time.Time
	Maxnumber         sql.NullInt32
	Format            sql.NullString
	Description       string
	Proposedatetime   time.Time
	Acceptadmin       int32
	Acceptdatetime    time.Time
	Applicationstatus string
}

type Activityrole struct {
	Activityid   int32
	Activityrole string
}

type Admin struct {
	Adminid int32
	Email   string
}

type Chatdevad struct {
	Messageid   int32
	Adminid     int32
	Developerid int32
	Message     string
	Datetime    time.Time
}

type Developer struct {
	Developerid int32
	Email       string
}

type Feedback struct {
	Feedbackid       int32
	Activityid       int32
	Memberid         int32
	Feedbackmessage  string
	Feedbackdatetime time.Time
}

type Member struct {
	Memberid       int32
	Fname          string
	Lname          string
	Email          string
	Phone          sql.NullString
	Githuburl      sql.NullString
	Interest       string
	Reason         string
	Acceptdatetime sql.NullTime
	Acceptadmin    int32
}

type Pjregist struct {
	Projectid   int32
	Memberid    int32
	Role        string
	Expectation string
	Datetime    time.Time
}

type Project struct {
	Projectid int32
	Advisor   sql.NullString
}

type Workshop struct {
	Workshopid int32
	Starttime  time.Time
	Endtime    time.Time
}

type Wsregist struct {
	Workshopid  int32
	Memberid    int32
	Role        string
	Expectation string
	Datetime    time.Time
}
